title: "Papers We Love Zürich"
description: "A Papers We Love chapter in Zürich, Switzerland."

# If you publish this repo as a *project* site (https://<user>.github.io/<repo>/),
# set baseurl to "/<repo>".
baseurl: ""
url: ""

permalink: pretty
markdown: kramdown
kramdown:
  input: GFM
